custom:
  prod:
    redis:
      host: fly-otg-redis-1.upstash.io
      port: 6379
      username: default
      password: c7bc3450261f438eb12b3a5384ed3272
    db:
      password: wiz20j9SoGGqJOb
  mail:
    username: tripnoteapi@gmail.com
    password: hufo hqua dnud hqjg
  tourapi:
    service-key: zRlL9l8h%2FwH3CNmsgxM%2FBxMvV6Z%2BEcMkFu%2B%2Fhhz5nUinQ5nO%2FiPAR5j3loBCB20USgqKggLVDO9HS33RnDU%2Fng%3D%3D