#custom:
#  prod:
#    redis:
#      host: fly-otg-redis-1.upstash.io
#      port: 6379
#      username: default
#      password: c7bc3450261f438eb12b3a5384ed3272
#    db:
#      password: wiz20j9SoGGqJOb